package nl.commutr.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActiehouderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActiehouderAllPropertiesEquals(Actiehouder expected, Actiehouder actual) {
        assertActiehouderAutoGeneratedPropertiesEquals(expected, actual);
        assertActiehouderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActiehouderAllUpdatablePropertiesEquals(Actiehouder expected, Actiehouder actual) {
        assertActiehouderUpdatableFieldsEquals(expected, actual);
        assertActiehouderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActiehouderAutoGeneratedPropertiesEquals(Actiehouder expected, Actiehouder actual) {
        assertThat(expected)
            .as("Verify Actiehouder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActiehouderUpdatableFieldsEquals(Actiehouder expected, Actiehouder actual) {
        assertThat(expected)
            .as("Verify Actiehouder relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActiehouderUpdatableRelationshipsEquals(Actiehouder expected, Actiehouder actual) {}
}
