package nl.commutr.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InwonerplanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInwonerplanAllPropertiesEquals(Inwonerplan expected, Inwonerplan actual) {
        assertInwonerplanAutoGeneratedPropertiesEquals(expected, actual);
        assertInwonerplanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInwonerplanAllUpdatablePropertiesEquals(Inwonerplan expected, Inwonerplan actual) {
        assertInwonerplanUpdatableFieldsEquals(expected, actual);
        assertInwonerplanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInwonerplanAutoGeneratedPropertiesEquals(Inwonerplan expected, Inwonerplan actual) {
        assertThat(expected)
            .as("Verify Inwonerplan auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInwonerplanUpdatableFieldsEquals(Inwonerplan expected, Inwonerplan actual) {
        assertThat(expected)
            .as("Verify Inwonerplan relevant properties")
            .satisfies(e -> assertThat(e.getBsn()).as("check bsn").isEqualTo(actual.getBsn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInwonerplanUpdatableRelationshipsEquals(Inwonerplan expected, Inwonerplan actual) {
        assertThat(expected)
            .as("Verify Inwonerplan relationships")
            .satisfies(e -> assertThat(e.getHoofddoel()).as("check hoofddoel").isEqualTo(actual.getHoofddoel()))
            .satisfies(e -> assertThat(e.getAanbod()).as("check aanbod").isEqualTo(actual.getAanbod()));
    }
}
